name: task
on:
  pull_request:
  schedule:
    - cron: '0 17 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -c release
      - name: Cache build binary
        uses: actions/cache@v3
        env:
          cache-name: cache-build-binary
        with:
          path: "./.build/release/TitechOCWScraping"
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
  run1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore build binary
        uses: actions/cache@v3
        env:
          cache-name: cache-build-binary
        with:
          path: "./.build/release/TitechOCWScraping"
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./.build/release/TitechOCWScraping --start 202300001  --end 202309999 --bucket titechapp-data --directory /courseinfo/courses
  run2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Restore build binary
        uses: actions/cache@v3
        env:
          cache-name: cache-build-binary
        with:
          path: "./.build/release/TitechOCWScraping"
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./.build/release/TitechOCWScraping --start 202310000  --end 202340000 --bucket titechapp-data --directory /courseinfo/courses
